apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-operator
  # annotations:
  #   argocd.argoproj.io/sync-wave: "0"
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: openshift-operators
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-pipeline
  # annotations:
  #   argocd.argoproj.io/sync-wave: "0"
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: openshift-operators
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
  # annotations:
  #   argocd.argoproj.io/sync-wave: "0"
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: openshift-operators
spec: {}
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: external-secrets
#   # annotations:
#   #   argocd.argoproj.io/sync-wave: "0"
#   labels:
#     openshift.io/cluster-monitoring: "true"
#     argocd.argoproj.io/managed-by: openshift-operators
# spec: {}