## Operator Install Helm Chart ##

namespace: openshift-operators

application:
   namespace: demo-app

name: openshift-gitops

version: "latest"

installPlanApproval: "Automatic"

source: "redhat-operators"

sourceNamespace: "openshift-marketplace"

## Instance customization ##
insecureEdgeTerminationPolicy: "Redirect"

termination: "reencrypt"

gitops:
   project:
       - name: hub
       - name: apps

gitrepo: https://github.com/rh-fran6/pipelines-demo.git