apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
  namespace: {{ .Values.pipelinsns }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi


