apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: redeploy-role-binding
  namespace: {{ .Values.appnamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: {{ .Values.appnamespace }}