apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipeline-vote-ui
  name: pipeline-vote-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-vote-ui
  template:
    metadata:
      labels:
        app: pipeline-vote-ui
    spec:
      containers:
        - image: quay.io/fanyaegb/pipeline-vote-ui:latest
          imagePullPolicy: Always
          name: pipeline-vote-ui
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9090
              protocol: TCP          
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: VOTING_API_SERVICE_HOST
              value: pipelines-vote-api
            - name: VOTING_API_SERVICE_PORT
              value: "9000"
