apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: pipeline-vote-ui
  name: pipeline-vote-ui
spec:
  host: vote-here.apps.dd-aro.eastus.aroapp.io
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: pipeline-vote-ui
    weight: 100


