apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalsecrets.appexternalsecretname }}
  namespace: {{ .Values.application.namespace }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.externalsecrets.appsecretstorename }}
    # namespace: {{ .Values.application.namespace }}
  target:
    name: {{ .Values.externalsecrets.apptargetsecret }}-value
  data:
  - secretKey: webhookSecret
    remoteRef:
      key: secret/webhookSecret