## ClusterSecretStore - For Read
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalsecrets.secretstorename }}
  namespace: {{ .Values.application.namespace }}
spec:
  provider:
    azurekv:
      tenantId: {{ .Values.eso.tenant_id }}
      vaultUrl: {{ .Values.eso.vault_url }}
      authSecretRef:
        clientId:
          name: {{ .Values.externalsecrets.secretname }}
          key: ClientID
          namespace: {{ .Values.application.namespace }}
        clientSecret:
          name: {{ .Values.externalsecrets.secretname }}
          key: ClientSecret
          namespace: {{ .Values.application.namespace }}
---
---
## ClusterSecretStore - For Push
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: akv-cluster-secret-read
  # annotations:
  #   argocd.argoproj.io/sync-wave: "3"
spec:
  provider:
    azurekv:
      tenantId: {{ .Values.eso.tenant_id }}
      vaultUrl: {{ .Values.eso.vault_url }}
      authSecretRef:
        clientId:
          name: akv-sp-read
          key: ClientID
          namespace: {{ .Values.application.namespace }}
        clientSecret:
          name: akv-sp-read
          key: ClientSecret
          namespace: {{ .Values.application.namespace }}