## ClusterSecretStore - For Read
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalsecrets.argocdsecretstorename }}
  namespace: {{ .Values.argocd_namespace}}
spec:
  provider:
    azurekv:
      tenantId: {{ .Values.eso.tenant_id }}
      vaultUrl: {{ .Values.eso.vault_url }}
      authSecretRef:
        clientId:
          name: {{ .Values.externalsecrets.pipelinesecretname }}
          key: ClientID
        clientSecret:
          name: {{ .Values.externalsecrets.pipelinesecretname }}
          key: ClientSecret
