## Read SP app ##
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalsecrets.appsecretname }}
  namespace: {{ .Values.application.namespace }}
type: Opaque
data:
  ClientID: {{ .Values.rbac_roles.read_client_id }}  
  ClientSecret: {{ .Values.rbac_roles.read_client_secret }} 

---
## Read SP pipeline##
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalsecrets.pipelinesecretname }}
  namespace: {{ .Values.pipeline.namespace }}
type: Opaque
data:
  ClientID: {{ .Values.rbac_roles.read_client_id }}  
  ClientSecret: {{ .Values.rbac_roles.read_client_secret }} 

---
---
## Read SP pipeline##
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalsecrets.argocdsecretname }}
  namespace: {{ .Values.argocd_namespace }}
type: Opaque
data:
  ClientID: {{ .Values.rbac_roles.read_client_id }}  
  ClientSecret: {{ .Values.rbac_roles.read_client_secret }} 