## Read SP ##
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalsecrets.secretname }}
  namespace: {{ .Values.application.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
  ClientID: {{ .Values.rbac_roles.read_client_id }}  
  ClientSecret: {{ .Values.rbac_roles.read_client_secret }} 
