apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webhook-secret-akv-read
  namespace: {{ .Values.pipeline.namespace }}
  # annotations:
  #   argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.externalsecrets.secretstorename }}
  target:
    name: webhook-secret
  data:
  - secretKey: webhookSecret
    remoteRef:
      key: secret/webhookSecret
  - secretKey: repoUname
    remoteRef:
      key: secret/repoUname
  - secretKey: repoPassword
    remoteRef:
      key: secret/repoPassword