## ClusterSecretStore - For Read
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalsecrets.pipelinesecretstorename }}
  namespace: {{ .Values.pipeline.namespace }}
spec:
  provider:
    azurekv:
      tenantId: {{ .Values.eso.tenant_id }}
      vaultUrl: {{ .Values.eso.vault_url }}
      authSecretRef:
        clientId:
          name: {{ .Values.externalsecrets.secretname }}
          key: ClientID
          namespace: {{ .Values.application.namespace }}
        clientSecret:
          name: {{ .Values.externalsecrets.secretname }}
          key: ClientSecret
          namespace: {{ .Values.application.namespace }}
