apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalsecrets.registryexternalsecretname }}
  namespace: {{ .Values.pipeline.namespace }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.externalsecrets.pipelinesecretstorename }}
  target:
    name: {{ .Values.externalsecrets.registrytargetsecret }}-value
  data:
  - secretKey: config.json
    remoteRef:
      key: secret/registryCred
  - secretKey: SONARHOSTURL
    remoteRef:
      key: secret/SONARHOSTURL
  - secretKey: SONARPROJECTKEY
    remoteRef:
      key: secret/SONARPROJECTKEY
  # - secretKey: SONAR_ORGANIZATION
  #   remoteRef:
  #     key: secret/SONARORGANIZATION