apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalsecrets.registryexternalsecretname }}
  namespace: {{ .Values.argocd_namespace }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.externalsecrets.pipelinesecretstorename }}
  target:
    name: {{ .Values.externalsecrets.registrytargetsecret }}-value
  data:
  - secretKey: config.json
    remoteRef:
      key: secret/registryCred