apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalsecrets.webhookexternalsecretname }}
  namespace: {{ .Values.pipeline.namespace }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.externalsecrets.pipelinesecretstorename }}
  target:
    name: {{ .Values.externalsecrets.webhooktargetsecret }}-value
  data:
  - secretKey: webhookSecret
    remoteRef:
      key: secret/webhookSecret