## Operator Install Helm Chart ##

namespace: openshift-gitops

# application:
#    namespace: demo-app

hub:
   namespace: demo-hub

projects:
  - name: pipeline
  - name: demo-app
  - name: infra

clusterdomain: apps.dd-aro.eastus.aroapp.io