## Operator Install Helm Chart ##

installnamespace: openshift-operators

defaultargo:
   namespace: openshift-gitops
   server: https://kubernetes.default.svc
   name: main-components
   project: default
   app:
     - name: namespace-creation
       repourl: https://github.com/rh-fran6/pipelines-demo.git
       targetrevision: main
       path: 03-applications/02-main-gitops-apps/namespaces

     - name: eso-install
       repourl: https://github.com/rh-fran6/pipelines-demo.git
       targetrevision: main
       path: 03-applications/02-main-gitops-apps/operators-install/external-secrets-operator
     
     - name: pipelines-install
       repourl: https://github.com/rh-fran6/pipelines-demo.git
       targetrevision: main
       path: 03-applications/02-main-gitops-apps/operators-install/openshift-pipelines
     
     - name: prep-tasks
       repourl: https://github.com/rh-fran6/pipelines-demo.git
       targetrevision: main
       path: 03-applications/02-main-gitops-apps/prep-tasks


hubargo:
  namespace: demo-hub
  server: https://kubernetes.default.svc
  app:
     - name: backend-voting-app
       repourl: https://github.com/rh-fran6/pipelines-demo.git
       project: demo-app
       destinationns: demo-app
       app: pipeline-vote-ui
       targetrevision: main
       path: 03-applications/01-config-gitops-apps/backend-deploy/overlays

     - name: frontend-voting-app
       repourl: https://github.com/rh-fran6/pipelines-demo.git
       project: demo-app
       destinationns: demo-app
       app: pipeline-vote-ui
       targetrevision: main
       path: 03-applications/01-config-gitops-apps/frontend-deploy/overlays

     - name: external-secrets-operator
       repourl: https://github.com/rh-fran6/pipelines-demo.git
       project: infra
       destinationns: demo-app
       targetrevision: main
       path: 03-applications/01-config-gitops-apps/operator-configs/eso

     - name: pipelines-config
       repourl: https://github.com/rh-fran6/pipelines-demo.git
       project: pipeline
       destinationns: demo-pipeline
       targetrevision: main
       path: 03-applications/01-config-gitops-apps/operator-configs/pipelines

    
