{{ $namespace := .Values.namespace }}
{{- range $key, $value := .Values.projects }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: {{ $namespace }}
spec:
  description: "GitOps for OpenShift Pipelines Demo"
  sourceNamespaces: 
    - demo-hub
#   destinations:
#   - namespace: '*'
#     server: '*'
#   clusterResourceWhitelist:
#   - group: '*'
#     kind: '*'
#   namespaceResourceWhitelist:
#   - group: '*'
#     kind: '*'
#   sourceRepos:
#   - '*'
# status: {}
---
{{- end }}

