{{ $namespace := .Values.hub.namespace }}
{{- range $key, $value := .Values.projects }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: {{ $namespace }}
spec:
  description: "GitOps for OpenShift Pipelines Demo"
  destinations:
  - namespace: demo-app
    server: https://kubernetes.default.svc
  - namespace: demo-hub
    server: https://kubernetes.default.svc
  - namespace: external-secrets-operator
    server: https://kubernetes.default.svc
  - namespace: demo-pipeline
    server: https://kubernetes.default.svc
  # destinations:
  # - namespace: '*'
  #   server: '*'
  # clusterResourceWhitelist:
  # - group: '*'
  #   kind: '*'
  # namespaceResourceWhitelist:
  # - group: '*'
  #   kind: '*'
  sourceRepos:
  - '*'
status: {}
---
{{- end }}

