apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redeploy-sa-demo-app
  namespace: demo-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: User
  name: client
- kind: ServiceAccount
  name: pipeline
  namespace: demo-pipeline