apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: vote-trigger
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: akv-pipeline-secret-value
            secretKey: webhookSecret
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: vote-app
  template:
    ref: vote-app
---

## Move to AKV ##
# apiVersion: v1
# kind: Secret
# metadata:
#   name: github-secret
# type: Opaque
# stringData:
#   secretToken: "pipelinestest"
