apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gitreposa }}
secrets:
  - name: {{ .Values.externalsecrets.pipelinetargetsecret }}-value

---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: my-scc is a close replica of anyuid scc. pipelines-scc has fsGroup - RunAsAny.
  name: my-custom-scc
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret

---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: {{ .Values.gitreposa }} 
#   namespace: demo-pipeline
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: pipelines-scc-clusterrole 
# subjects:
# - kind: ServiceAccount
#   name: pipeline
#   namespace: demo-pipeline

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: pipelines-scc-clusterrole 
# rules:
# - apiGroups:
#   - security.openshift.io
#   resourceNames:
#   - nonroot
#   resources:
#   - securitycontextconstraints
#   verbs:
#   - use