apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: {{ .Values.event_listener_name }}
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.head_commit.id)

---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: buildah-task-copy
spec:
  taskRunTemplate:
    serviceAccountName:  {{ .Values.gitreposa }}
  taskRef:
    name: buildah