replicaCount: 1
## Operator Install Helm Chart ##

externalsecrets:
  externalsecretname: webhook-secret-akv-read
  externalsecretns: demo-app
  secretstorename: akv-cluster-secret-read
  secretname: akv-sp-read
  operatornamespace: openshift-operators
  pipelinesecretname: pipeline-secret-akv-read

application:
  namespace: demo-app

pipeline:
   namespace: demo-pipeline

eso:
  tenant_id: 64dc69e4-d083-49fc-9569-ebece1dd1408
  vault_url: https://dd-aro-cluster-akv-demo.vault.azure.net

rbac_roles:
   read_client_id: Y2ZhMjI0YWQtMzcwZS00MjhhLWFlMjctYmMxMTIyMzQ0NWNiCg==
   read_client_secret: RDFrOFF+cX45YjFRTEx3LktEUUdDN3FSSlhSaWpxZHhPYUI1Z2NNNgo=