replicaCount: 1
## Operator Install Helm Chart ##

externalsecrets:
  externalsecretname: webhook-secret-akv-read
  externalsecretns: demo-app
  secretstorename: akv-cluster-secret-read
  secretname: akv-sp-read
  operatornamespace: openshift-operators
  reposecretname: repo-secret-akv-read

application:
  namespace: demo-app

pipeline:
   namespace: demo-pipeline

eso:
  tenant_id: 64dc69e4-d083-49fc-9569-ebece1dd1408
  vault_url: https://dd-aro-cluster-akv-demo.vault.azure.net

imageregistry: https://quay.io/repository/fanyaegb/pipelines-demo

rbac_roles:
  read_client_id: YzBmZTQwNTgtZmM4NS00ZGI5LWJjNWUtNDE0YTdjYTg0ZjZmCg==
  read_client_secret: S1RVOFF+aVBKQl9KUlFvfmguUHR1S2pBXzNmM3NGN0NoQ3BpZGI4Ygo=