{{ $hubnamespace := .Values.hubargo.namespace }}
{{ $hubserver := .Values.hubargo.server }}
{{- range $key, $value := .Values.hubargo.app }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: ui-alias=quay.io/fanyaegb/pipeline-vote-ui:latest
    argocd-image-updater.argoproj.io/ui-alias.update-strategy: digest
    argocd-image-updater.argoproj.io/image-list: api-alias=quay.io/fanyaegb/pipeline-vote-api:latest
    argocd-image-updater.argoproj.io/api-alias.update-strategy: digest
  name: {{ .name }}
  namespace: {{ $hubnamespace }}
spec:
  destination:
    server: {{ $hubserver }}
    namespace: {{ .destinationns }}  
  project: {{ .project }}
  sources:
    - repoURL: {{ .repourl }}
      targetRevision: {{ .targetrevision }}
      path: {{ .path }}
  syncPolicy:
    automated:
       prune: true
       selfHeal: true
    retry:
      limit: 20
---
{{- end }}
