{{ $hubnamespace := .Values.hubargo.namespace }}
{{ $hubserver := .Values.hubargo.server }}
{{- range $key, $value := .Values.hubargo.app }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
  # {{- if .app -}}
    argocd-image-updater.argoproj.io/image-list: image-alias=quay.io/fanyaegb/{{ .deploy }}:latest
    argocd-image-updater.argoproj.io/ui-alias.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git  
    argocd-image-updater.argoproj.io/git-branch: main 
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
  # {{- end }}
  name: {{ .name }}
  namespace: {{ $hubnamespace }}
spec:
  destination:
    server: {{ $hubserver }}
    namespace: {{ .destinationns }}  
  project: {{ .project }}
  sources:
    - repoURL: {{ .repourl }}
      targetRevision: {{ .targetrevision }}
      path: {{ .path }}
  syncPolicy:
    automated:
       prune: true
       selfHeal: true
    retry:
      limit: 20
---
{{- end }}
