apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - hubnamespace.yaml
  - ../base

patches:
  - target:
      kind: Subscription
      name: openshift-gitops-operator
    path: patch-channel.yaml
